mcs.metadata:
  componentName: post_application_message
kind: TaskDialog
outputs:
  - propertyName: status

  - propertyName: applicationId

  - propertyName: messageId

  - propertyName: message

action:
  kind: InvokeFlowTaskAction
  flowId: 3dfc08d1-7e92-f111-b8db-7c1e524a54ce
  connectionProperties:
    $kind: ConnectionProperties
    diagnostics:
    mode: Invoker

outputMode: All